defaults:
  - _self_
  - resources: null

# experiment params
NUM_SEEDS: 1
SEED: 0

# if  hyperparameters tuning
HYP_TUNE: False
LOGGING:
  MODE: "full_train" # full_train, test, train

# wandb params
WANDB_MODE: "disabled"  # set to online to activate wandb
ENTITY: ""
PROJECT: ""
alg:
  WANDB_LOG_ALL_SEEDS: False # will log all the vmapped seeds separetely

# where to save the params (if None, will not save)
SAVE_PATH: "./models"


hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${alg.ALG_NAME}
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_continual_rl_atari_three_games
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    mem_gb: 16
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_continual_rl_atari_three_games/.slurm
